services:
    db:
        container_name:
            db
        image:
            postgres:alpine
        restart:
            unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        healthcheck:
            test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        deploy:
            resources:
                limits:
                    cpus: "0.2"
                    memory: 200M
    api:
        container_name:
            api
        build:
            context:
                .
            dockerfile:
                Dockerfile
        restart:
            unless-stopped
        command:
            python tasks/manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        depends_on:
            - db
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 500M
volumes:
    postgres-data:
